### ISSUE TITLE
How to get cwd in runner script?

### ISSUE THREAD

**Issue by rrthomas** [CS-SI/pytest-executable#21]
In the example in `https://pytest-executable.readthedocs.io/en/stable/usage.html#command-line-interface` is the line:

```
exe=/path/to/executable
```

I guess that often one will want to find the executable relative to the project in which the tests are. For example, an executable in the root directory of my Python project. I can't find out how to do this (apologies, I am new to both pytest and pytest-executable).

If all my tests are at the same directory level, I can use

```
exe=../../executable
```

with the appropriate number of `..` levels; but in general, this won't work.

Thanks for `pytest-executable`!

**Comment by AntoineD** [comment]
HI @rrthomas,
from my experience, it is generally safer and less error prone to use absolute paths.

That being said, I would also say that it's not easy to inject a computed path into the runner script, but I haven't used this plugin for a while so I could overlook something.

You could perhaps use this kind of [bash trick](https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script) to determine the location of an executed runner script and adjust the path to the executable in the runner script.

**Comment by AntoineD** [comment]
Would it be possible for you to share your test files so I can have a look?

**Comment by rrthomas** [comment]
@AntoineD, thanks for your suggestions! I'm not sure how I could use an absolute path when I don't know where a user might be trying to build and run the tests of my program.

My project is at https://github.com/rrthomas/rpl and the test runner is at https://github.com/rrthomas/rpl/blob/master/tests/test-runner.sh

The program being tested is the single executable Python script that is installed by this project. As you can see in line 3 of the test runner, currently I just invoke it by relative directory, relying on the fact that currently all my tests are in subdirectories of the `tests` directory, which itself is in the same directory as the script being tested.

**Comment by AntoineD** [comment]
Would the following work for you?

Using an environment variable that points to the executable:
```bash
> cat tests/test-runner.sh                                
#!/bin/sh

$EXE \
	{{rpl_options}} < input.txt \
	1> executable.stdout \
	2> executable.stderr
grep {{grep_options}} "{{grep_pattern}}" {{grep_file}}
```
and in the terminal where pytest is ran
```bash
export EXE=$(pwd)/rpl
```

**Comment by rrthomas** [comment]
Thanks for the suggestion! To use it it would seem I either need an extra manual step (literally execute the `export` command in my shell), which is not great (again, I'm thinking of users installing the package—I don't want to require them to have to execute an extra, non-standard, command); or, I need to have the `export` command elsewhere.

Currently, there's an obvious place to add the `export` command in my project, namely in the `Makefile`, under the `check` target. I was hoping to get rid of the `Makefile`, and only use `setuptools` facilities, but since `setuptools` has explicitly deprecated the `test` command, `make check` might be the "most standard" interface I can offer users anyway.

**Comment by gbonnefille** [comment]
IMHO, the better way to achieve this is to compute the path to exe inside the `test-runner.sh` based on the location of the `test-runner.sh` itself. This way you both have an absolute path computed with a relative logic.

```SH
> cat tests/test-runner.sh                                
#!/bin/sh
MYPATH=...see-more...
$MYPATH/../rpl \
	{{rpl_options}} < input.txt \
	1> executable.stdout \
	2> executable.stderr
grep {{grep_options}} "{{grep_pattern}}" {{grep_file}}
```

There are plenty of way to achieve this, depending on the prerequisites of the environment: https://linuxhint.com/absolute-path-script-bash/

@AntoineD it is probably a common use case and it is perhaps a good idea to propose a solution in the documentation?

**Comment by AntoineD** [comment]
Hi @gbonnefille,

isn't it similar to what I suggested [above](https://github.com/CS-SI/pytest-executable/issues/21#issuecomment-1268694867)?

@rrthomas
Setting the `EXE` environment variable in the `Makefile` looks good to me.
Besides, I'm not sure `setuptools` is the right tool for replacing a `Makefile`, you may use [tox](https://tox.wiki/en/latest/) instead. (`pytest-executable` uses it).
You may also use a `tests/__init__.py` to set the environment variable that points to the executable.

**Comment by gbonnefille** [comment]
@AntoineD I understood you suggested to add a dependency from outside the script: a $EXE defined previously, in shell, before running command. The comment you linked is the **unique** *simple* solution.

One example, in *bash*:
```SH
> cat tests/test-runner.sh  
#!/bin/bash
MYPATH=$(cd $(dirname “${BASH_SOURCE:-$0}”) && pwd)
$MYPATH/../rpl \
	{{rpl_options}} < input.txt \
	1> executable.stdout \
	2> executable.stderr
grep {{grep_options}} "{{grep_pattern}}" {{grep_file}}
```

With such script, you can run it from projectdir/tests, from projectdir/path, from projectdir/tests/test1... with a releative path (./test-runner.sh) or with an absolute path (projectdir/tests/test-runner.sh)... it will always retrieve its own directory and so it will always define an absolute path to rpl... without requiring any external help.

**Comment by AntoineD** [comment]
It was suggesting this among several solutions, personally I would go for this self introspection in the bash script too. :+1:

**Comment by rrthomas** [comment]
Thanks both; the portable (if slightly long-winded) solution in the bash script looks best to me too. Since it's non-obvious, it would be great to have it in the documentation.

I am indeed using tox!

@gbonnefille, some curly quotes got into your example code above!

Unfortunately, the solution given does not work well for me: the `test-runner.sh` script is copied into the test directory, so the value of `MYPATH` is simply the test directory, which is not at a known place in the file hierarchy.

**Comment by rrthomas** [comment]
Since I'm using tox, I put the following in my `tox.ini`:

```
[testenv]
commands = /usr/bin/env TOPDIR={toxinidir} pytest --exe-clean-output --exe-runner tests/test-runner.sh
```

This sets `TOPDIR` correctly, and I can then use `$TOPDIR/rpl` in my `test-runner.sh`.

**Comment by AntoineD** [comment]
I'll update the documentation, thank you for raising this question.

FYI, the [natural way](https://tox.wiki/en/latest/config.html#conf-setenv) to set an environment variable in `tox.ini` would be:
```bash
[testenv]
setenv =
    TOPDIR = {toxinidir}
commands = pytest --exe-clean-output --exe-runner tests/test-runner.sh
```

**Comment by rrthomas** [comment]
Thanks for the tip!
