### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by rrthomas** [CS-SI/pytest-executable#24]
When using pytest-executable 0.5.4 (the latest version at time of writing), I get deprecation messages like this:

```
.tox/py311/lib/python3.11/site-packages/pytest_executable/plugin.py:299
  /home/rrt/Software/rpl/.tox/py311/lib/python3.11/site-packages/pytest_executable/plugin.py:299: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to TestExecutableModule is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return TestExecutableModule.from_parent(parent, fspath=path)
```

I am guessing that the developers are aware of this issue, since pytest v7 support was explicitly added to pytest-executable 0.5.4.

While this isn't a serious problem until the deprecated parameters are droped in pytest v8, it does make tox output harder to read confidently, as it causes tox to complain about the warnings.

**Comment by rrthomas** [comment]
Many thanks for the quick fix!

**Comment by AntoineD** [comment]
You're welcome, the version 0.5.5 is now available with the fix.
